from PIL import Image
import numpy as np

tiles_dir = "../../assets/mario"
chars2pngs = {
    "-": Image.open(f"{tiles_dir}/smb-background.png"),
    "X": Image.open(f"{tiles_dir}/ground.png"),
    "#": Image.open(f"{tiles_dir}/smb-unpassable.png"),
    "S": Image.open(f"{tiles_dir}/smb-breakable.png"),
    "?": Image.open(f"{tiles_dir}/special_question_block.png"),
    "Q": Image.open(f"{tiles_dir}/special_question_block.png"),
    "o": Image.open(f"{tiles_dir}/coin.png"),
    "E": Image.open(f"{tiles_dir}/blue_goomba.png"),
    "<": Image.open(f"{tiles_dir}/smb-tube-top-left.png"),
    ">": Image.open(f"{tiles_dir}/smb-tube-top-right.png"),
    "(": Image.open(f"{tiles_dir}/white_pipe_top_left.png"),
    ")": Image.open(f"{tiles_dir}/white_pipe_top_right.png"),
    "[": Image.open(f"{tiles_dir}/smb-tube-lower-left.png"),
    "]": Image.open(f"{tiles_dir}/smb-tube-lower-right.png"),
    "x": Image.open(f"{tiles_dir}/smb-path.png"),
    "Y": Image.fromarray(np.uint8(np.zeros((16, 16)))),
    "N": Image.open(f"{tiles_dir}/N.png"),
    "B": Image.open(f"{tiles_dir}/cannon_top.png"),
    "b": Image.open(f"{tiles_dir}/cannon_bottom.png"),
    "F": Image.open(f"{tiles_dir}/icon_interrogation.png"),
    "C": Image.open(f"{tiles_dir}/yellow_brick.png"),
    "U": Image.open(f"{tiles_dir}/red_brick.png"),
    "!": Image.open(f"{tiles_dir}/smb-question.png"),
    "L": Image.open(f"{tiles_dir}/life.png"),
    "2": Image.open(f"{tiles_dir}/coin2.png"),
    "g": Image.open(f"{tiles_dir}/goomba.png"),
    "G": Image.open(f"{tiles_dir}/white_goomba.png"),
    "k": Image.open(f"{tiles_dir}/koopa.png"),
    "K": Image.open(f"{tiles_dir}/winged_koopa.png"),
    "r": Image.open(f"{tiles_dir}/red_koopa.png"),
    "R": Image.open(f"{tiles_dir}/winged_red_koopa.png"),
    "y": Image.open(f"{tiles_dir}/spiny.png"),
    "t": Image.open(f"{tiles_dir}/icon_interrogation.png"),
    "T": Image.open(f"{tiles_dir}/icon_interrogation.png"),
}